;; Start consult-line search with symbol at point
;; https://github.com/minad/consult/wiki#start-consult-line-search-with-symbol-at-point
(defun consult-line-symbol-at-point ()
  (interactive)
  (consult-line (thing-at-point 'symbol)))

(defun consult-line-literal ()
  (interactive)
  (let ((completion-styles '(fussy basic)))
    (consult-line)))

(defun my/convert-vim-regexp-to-emacs (regexp)
  (let ((conversion-table '(("\\\\<" . "")
                          ("\\\\>" . ""))))
    (dolist (pair conversion-table regexp)
      (setq regexp (replace-regexp-in-string (car pair) (cdr pair) regexp t t)))))

(defun my/evil-search-to-isearch ()
  (interactive)
  (if (evil-ex-p)
      (let* ((search-string (minibuffer-contents))
             (converted-string (convert-vim-regexp-to-emacs search-string)))
        (abort-recursive-edit)
        (isearch-mode t)
        (isearch-yank-string converted-string))
    (let* ((search-string (car evil-ex-search-history))
           (converted-string (convert-vim-regexp-to-emacs search-string)))
      (isearch-mode t)
      (isearch-yank-string converted-string))))

(defun my/isearch (prefix)
  (interactive "p")
  (cond ((eq prefix 1)
         (call-interactively 'isearch-forward))
        ((eq prefix 4)
         (call-interactively 'consult-line))
        ((eq prefix 16)
         (call-interactively 'consult-line-symbol-at-point))))
